In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/creditcard.csv")

In [3]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0


In [4]:
df.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(1081)

In [6]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

# train test split :

In [7]:
X = df.iloc[: , :-1]
y = df.iloc[:, -1]

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# preprocessing operations that learn from data :

In [9]:
y_train.value_counts()    # <<imbalanced class>> !!!!

Class
0    226602
1       378
Name: count, dtype: int64

In [10]:
train_df = X_train.copy()
train_df["Class"] = y_train

In [11]:
legit = train_df[train_df["Class"] == 0]
legit.shape

(226602, 31)

In [12]:
fraud = train_df[train_df["Class"] == 1]
fraud.shape

(378, 31)

# Undersampling :

In [13]:
sampled_legit = legit.sample(fraud.shape[0])
sampled_legit.shape

(378, 31)

In [14]:
balanced_df = pd.concat([sampled_legit, fraud], axis=0)
balanced_df.shape

(756, 31)

In [15]:
X_train = balanced_df.drop("Class", axis=1)
y_train = balanced_df['Class']

In [16]:
X_train.shape

(756, 30)

In [17]:
y_train.shape

(756,)

# Scaling :

In [18]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)

X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

# Logistic Regression :

In [19]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_score = accuracy_score(y_test, y_pred)

confusion_matrix = confusion_matrix(y_test, y_pred)

classification_report = classification_report(y_test, y_pred)

print(f"accuracy_score : {accuracy_score} \n confusion matrix : \n {confusion_matrix}")

print(classification_report)

accuracy_score : 0.9749409650019385 
 confusion matrix : 
 [[55241  1410]
 [   12    83]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56651
           1       0.06      0.87      0.10        95

    accuracy                           0.97     56746
   macro avg       0.53      0.92      0.55     56746
weighted avg       1.00      0.97      0.99     56746



# KNN :

In [26]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier()
knn_model.fit(X_train, y_train)

y_pred = knn_model.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_score = accuracy_score(y_test, y_pred)

confusion_matrix = confusion_matrix(y_test, y_pred)

classification_report = classification_report(y_test, y_pred)

print(f"accuracy_score : {accuracy_score} \n confusion matrix : \n {confusion_matrix}")
print(classification_report)

accuracy_score : 0.9783773305607444 
 confusion matrix : 
 [[55442  1209]
 [   18    77]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56651
           1       0.06      0.81      0.11        95

    accuracy                           0.98     56746
   macro avg       0.53      0.89      0.55     56746
weighted avg       1.00      0.98      0.99     56746



# SVC :

In [28]:
from sklearn.svm import SVC

svc_model = SVC()
svc_model.fit(X_train, y_train)

y_pred = svc_model.predict(X_test)

In [29]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_score = accuracy_score(y_test, y_pred)

confusion_matrix = confusion_matrix(y_test, y_pred)

classification_report = classification_report(y_test, y_pred)

print(f"accuracy_score : {accuracy_score} \n confusion matrix : \n {confusion_matrix}")
print(classification_report)

accuracy_score : 0.9781834842984527 
 confusion matrix : 
 [[55427  1224]
 [   14    81]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56651
           1       0.06      0.85      0.12        95

    accuracy                           0.98     56746
   macro avg       0.53      0.92      0.55     56746
weighted avg       1.00      0.98      0.99     56746



# Random Forest :

In [32]:
from sklearn.ensemble import RandomForestClassifier

model_rf = RandomForestClassifier()

model_rf.fit(X_train, y_train)

y_pred = model_rf.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_score = accuracy_score(y_test, y_pred)

confusion_matrix = confusion_matrix(y_test, y_pred)

classification_report = classification_report(y_test, y_pred)

print(f"accuracy_score : {accuracy_score} \n confusion matrix : \n {confusion_matrix}")
print(classification_report)

accuracy_score : 0.9691960666831142 
 confusion matrix : 
 [[54915  1736]
 [   12    83]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     56651
           1       0.05      0.87      0.09        95

    accuracy                           0.97     56746
   macro avg       0.52      0.92      0.54     56746
weighted avg       1.00      0.97      0.98     56746



# XGBoost :

In [30]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier()
xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy_score = accuracy_score(y_test, y_pred)

confusion_matrix = confusion_matrix(y_test, y_pred)

classification_report = classification_report(y_test, y_pred)

print(f"accuracy_score : {accuracy_score} \n confusion matrix : \n {confusion_matrix}")
print(classification_report)

accuracy_score : 0.962199978853135 
 confusion matrix : 
 [[54519  2132]
 [   13    82]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     56651
           1       0.04      0.86      0.07        95

    accuracy                           0.96     56746
   macro avg       0.52      0.91      0.53     56746
weighted avg       1.00      0.96      0.98     56746



- i'll choose the model with best **recall** ! , because i'll consider classifing a **fraud** as **legitimate** is more **costly**
- which is : **random forest**

# Deploying model & scaler :

In [23]:
import joblib

joblib.dump(model_rf, "../model/model.pkl")
joblib.dump(sc, "../model/scaler.pkl")

['../model/scaler.pkl']